server:
  port: 5050
spring:
  datasource:
    password: Temp1234
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
  jpa:
    hibernate:
      ddl-auto: create

  application:
    name: coupon-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false