#spring.datasource.url=jdbc://localhost:3306/javabatch

#spring.datasource.username=root 

#spring.datasource.password=Temp1234
#spring.jpa.hibernate.ddl-auto=create
server:
  port: 6060
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/javabatch
  username: root
  password: Temp1234
 jpa:
  hibernate:
   ddl-auto: create
  show-sql: true
  properties:
   hibernate:
   formate_sql: true
  # database-platform: org.hibernate.dialect.MySQL5Dialect

  
 
  
  
 
   